### ISSUE TITLE
load_binary() function renamed

### ISSUE THREAD

**Issue by Erikpostt** [biomarkersParkinson/tsdf#16]
I can't locate the load_binary() function in the [.ipynb example](https://github.com/biomarkersParkinson/tsdf/blob/main/docs/processing_example.ipynb) src code. I think it got renamed to .load_binary_from_metadata() but I'm not sure.

![image](https://github.com/biomarkersParkinson/tsdf/assets/57133568/21c080aa-2272-4e49-9c12-860e4396f1ac)

**Comment by Erikpostt** [comment]
I found it. I wasn't aware of the function being part of the _TSDFMetadata_ class in [the _tsdf_metadata.py_ file](https://github.com/biomarkersParkinson/tsdf/blob/main/src/tsdf/tsdf_metadata.py)

**Comment by vedran-kasalica** [comment]
The example is using the TSDF method [load_binary()](https://github.com/biomarkersParkinson/tsdf/blob/6276d2035f14d7d1b3f914875233c40672b02412/src/tsdf/tsdf_metadata.py#LL66C17-L66C17), which in turn calls [load_binary_from_metadata()](https://github.com/biomarkersParkinson/tsdf/blob/6276d2035f14d7d1b3f914875233c40672b02412/src/tsdf/io.py#L61). The idea is that the tsdf_metadata object (dummy_data in the example) provides a direct method for loading the associated binary files.
