### ISSUE TITLE
pip install installation problems 

### ISSUE THREAD

**Issue by JordanRaykov** [biomarkersParkinson/tsdf#46]
I have noticed that the pip install option for the tsdf package does not really work for many configurations. It is not clear what environment it requires and executing prompts an error "No matching distribution found for tsdf"

**Comment by vedran-kasalica** [comment]
Hi @JordanRaykov, thanks for the feedback. The library requires Python version 3.9 or higher (we will emphasize that in the documentation). Could that be the issue?

**Comment by JordanRaykov** [comment]
Hi Vedran,

Yes, it was the lack of backward compatibility that was the problem for me.
I fixed it now by re-installing. I do have couple of questions though
regarding making the new converted files compatible with the tsdf loading
code you currently have. Would it be possible to schedule a quick 30
minute-1 hour call sometime next week to go over this, just to make sure
the newly generated meta files are readable by all groups?

Best,
Jordan
